# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
    node: circleci/node@4.1
    codecov: codecov/codecov@3.0.0

executors:
    node:
        docker:
            - image: cimg/node:16.2.0

jobs:
    test-frontend:
        executor: node
        steps:
            - checkout
            - node/install-npm
            - run: npm install
            - run: npm test
            - persist_to_workspace:
                root: .
                paths:
                    - coverage/coverage-final.json
            - codecov/upload

workflows:
    run-tests:
        jobs:
            - test-frontend
