import { Quote } from './InThePress.interfaces';

export const quotes: Quote[] = [
    {
        imagePath: '/images/press/TheWashingtonPost.svg',
        imageAlt: 'The Washington Post Logo',
        imageHeight: 46,
        imageWidth: 300,
        quoteURL: 'https://www.washingtonpost.com/business/2021/08/19/how-qualify-mortgage-with-uneven-income',
        catchPhrase: "What we have noticed is the performance of these loans are better than your traditional conventional loans.",
        remainder: "As the mortgage servicers who deal in non-QM loans establish positive performance trends, non-QM loan programs will continue to expand.",
        newsOutlet: 'The Washington Post',
    },
    {
        imagePath: '/images/press/yahoo.svg',
        imageAlt: 'Yahoo Logo',
        imageHeight: 55,
        imageWidth: 200,
        quoteURL: 'https://finance.yahoo.com/finance/news/prepare-housing-market-crash-2021-120051439.html',
        catchPhrase: "What’s different today from what we saw in 2008",
        remainder: "is that people who are qualifying for loans are actually qualified. They are creditworthy.",
        newsOutlet: 'Yahoo!',
    },
    {
        imagePath: '/images/press/USAToday.svg',
        imageAlt: 'USA Today Logo',
        imageHeight: 70,
        imageWidth: 300,
        quoteURL: 'https://www.usatoday.com/story/sponsor-story/mbanc/2021/03/22/how-unconventional-approach-mortgages-helped-two-entrepreneurs/4725567001',
        catchPhrase: "MBANC has a different view on how you should qualify for a mortgage.",
        remainder: "The lender personalizes the qualification process and looks at you holistically.",
        newsOutlet: 'USA Today',
    },
    {
        imagePath: '/images/press/TheSun.svg',
        imageAlt: 'The Sun Logo',
        imageHeight: 87,
        imageWidth: 200,
        quoteURL: 'https://www.the-sun.com/money/3288694/how-pay-off-mortgage-years-early',
        catchPhrase: "Although it might feel good to know you fully own your home,",
        remainder: "there might be more financially savvy places to put your money.",
        newsOutlet: 'The Sun',
    },
    {
        imagePath: '/images/press/USAToday.svg',
        imageAlt: 'USA Today Logo',
        imageHeight: 70,
        imageWidth: 300,
        quoteURL: 'https://www.usatoday.com/story/sponsor-story/mbanc/2021/02/18/self-employed-and-want-buy-home-process-easier-than-expected/6769814002',
        catchPhrase: "Because MBANC is funded by private investors looking for entrepreneurs to whom they can lend,",
        remainder: "it controls all of its loan analysis and decision-making.",
        newsOutlet: 'USA Today',
    },
    {
        imagePath: '/images/press/NationalMortgageNews.svg',
        imageAlt: 'National Mortgage News Logo',
        imageHeight: 25,
        imageWidth: 300,
        quoteURL: 'https://www.nationalmortgagenews.com/news/non-qm-lender-mbanc-underwrites-borrower-income-from-mobile-wallets',
        catchPhrase: "Mbanc is a direct-to-consumer non-qualified mortgage lender",
        remainder: "whose customer base includes business owners who accept online payments for their products and services.",
        newsOutlet: 'National Mortgage News',
    },
    {
        imagePath: '/images/press/Bankrate.svg',
        imageAlt: 'Bankrate News Logo',
        imageHeight: 60,
        imageWidth: 140,
        quoteURL: 'https://www.bankrate.com/mortgages/how-to-buy-a-house-with-low-income/',
        catchPhrase: '“There are a few other strings attached, too: If you are a first-time buyer,',
        remainder: 'you will be required to go through a homeownership education program,” adds Tabitha Mazzara',
        newsOutlet: 'Bankrate',
    },
    {
        imagePath: '/images/press/GoBankingRates.svg',
        imageAlt: 'GoBankingRates News Logo',
        imageHeight: 45,
        imageWidth: 180,
        quoteURL: 'https://www.gobankingrates.com/loans/mortgage/pros-cons-online-mortgage-lenders/',
        catchPhrase: 'We’ve made it easy to do everything from your couch',
        remainder: '',
        newsOutlet: 'GoBankingRates',
    },
    {
        imagePath: '/images/press/MSN.svg',
        imageAlt: 'MSN Logo',
        imageHeight: 45,
        imageWidth: 100,
        quoteURL: 'https://www.msn.com/en-us/money/realestate/how-to-buy-a-house-with-a-low-income/ar-AAPHtZ2',
        catchPhrase: 'There are a few other strings attached, too:',
        remainder: 'If you are a first-time buyer, you will be required to go through a homeownership education program," adds Tabitha Mazzara, director of operations at MBANC, a mortgage lender.',
        newsOutlet: 'MSN',
    },
    {
        imagePath: '/images/press/LendingTree.svg',
        imageAlt: 'LendingTree News Logo',
        imageHeight: 65,
        imageWidth: 180,
        quoteURL: 'https://www.lendingtree.com/home/mortgage/what-is-a-balloon-mortgage-loan',
        catchPhrase: 'I think that they would be solely for a savvy real estate investor',
        remainder: 'that understands how to move through the market and is comfortable with the terms within the balloon note',
        newsOutlet: 'LendingTree',
    },
    {
        imagePath: '/images/press/DailyNationToday.png',
        imageAlt: 'Daily Nation Today Logo',
        imageHeight: 42,
        imageWidth: 200,
        quoteURL: 'https://dailynationtoday.com/how-does-a-wraparound-mortgage-work',
        catchPhrase: 'The vendor will get the clear advantage',
        remainder: 'of the ability to cost an excessive fee of curiosity for a mortgage',
        newsOutlet: 'Daily Nation Today',
    },
    {
        imagePath: '/images/press/BusinessInsider.svg',
        imageAlt: 'Business Insider Logo',
        imageHeight: 47,
        imageWidth: 150,
        quoteURL: 'https://www.businessinsider.com/what-is-underwriting',
        catchPhrase: `"Underwriting is basically just verifying all of the information the borrower has provided on their loan application`,
        remainder: `— their income, their tax returns, their bank accounts and other assets," says Mayer Dallal`,
        newsOutlet: 'Business Insider',
    },
    {
        imagePath: '/images/press/GoBankingRates.svg',
        imageAlt: 'GoBankingRates News Logo',
        imageHeight: 45,
        imageWidth: 180,
        quoteURL: 'https://www.gobankingrates.com/investing/real-estate/why-holidays-are-good-time-to-buy-house',
        catchPhrase: `“If someone is selling during the holidays, it usually indicates they've already left their former home behind,`,
        remainder: `and they're spending the holidays elsewhere, so they have emotionally disassociated themselves from the home,” Mayer said`,
        newsOutlet: 'GoBankingRates',
    },
    {
        imagePath: '/images/press/CNBC.svg',
        imageAlt: 'CNBC Logo',
        imageHeight: 28,
        imageWidth: 180,
        quoteURL: 'https://www.cnbc.com/2021/12/02/aiming-to-buy-a-home-in-the-next-year-do-these-4-things.html',
        catchPhrase: `“It's tough to overstate the importance of credit scores to a mortgage loan application,”`,
        remainder: `says Tabitha Mazzara, director of operations at Mortgage Bank of California. “They're one of the top things lenders consider.”`,
        newsOutlet: 'CNBC',
    },
    {
        imagePath: '/images/press/NextAdvisor.svg',
        imageAlt: 'NextAdvisor Logo',
        imageHeight: 46,
        imageWidth: 200,
        quoteURL: 'https://time.com/nextadvisor/mortgages/energy-efficient-mortgages/',
        catchPhrase: `Business owners and homeowners are turning to financing options like green loans`,
        remainder: `or energy efficient mortgages so they can make eco-friendly and energy-saving improvements while saving money on their utility bills every month.”`,
        newsOutlet: 'NextAdvisor',
    },
    {
        imagePath: '/images/press/MSN.svg',
        imageAlt: 'MSN Logo',
        imageHeight: 45,
        imageWidth: 100,
        quoteURL: 'https://www.msn.com/en-us/money/realestate/the-number-of-us-cities-with-an-average-home-price-of-dollar1-million-tripled-last-year/ar-AAUd0Mt',
        catchPhrase: 'Look at any open house — they\'re crazy crowded.',
        remainder: 'The competition and demand is so high that even if you have government help, someone else might come in with 50% down.',
        newsOutlet: 'MSN',
    },
    {
        imagePath: '/images/press/Forbes.svg',
        imageAlt: 'Forbes Logo',
        imageHeight: 32,
        imageWidth: 131,
        quoteURL: 'https://www.forbes.com/advisor/mortgages/homes-for-sale-hit-record-low',
        catchPhrase: 'It\'s a true sellers\' market right now,',
        remainder: 'with more adherence to sellers\' demands than normal.',
        newsOutlet: 'Forbes',
    },
    {
        imagePath: '/images/press/Money.png',
        imageAlt: 'Money Logo',
        imageHeight: 45,
        imageWidth: 130,
        quoteURL: 'https://money.com/failed-homebuyers-return-trend-tips',
        catchPhrase: '"They\'re going to have to up their budgets," says Mayer Dallal, managing director at mortgage lender MBANC.',
        remainder: '"Interest rates are going to keep creeping up, and home prices may either continue to rise or may flatten, but I don\'t see them going down anytime soon. A budget that was reasonable a couple of months ago may not be as interest rates climb."',
        newsOutlet: 'Money',
    },
];
