import { Quote } from './InThePress.interfaces';

export const quotes: Quote[] = [
    {
        imagePath: '/images/press/TheWashingtonPost.svg',
        imageAlt: 'The Washington Post Logo',
        imageHeight: 46,
        imageWidth: 300,
        quoteURL: 'https://www.washingtonpost.com/business/2021/08/19/how-qualify-mortgage-with-uneven-income',
        catchPhrase: "What we have noticed is the performance of these loans are better than your traditional conventional loans.",
        remainder: "As the mortgage servicers who deal in non-QM loans establish positive performance trends, non-QM loan programs will continue to expand.",
        newsOutlet: 'The Washington Post',
    },
    {
        imagePath: '/images/press/yahoo.svg',
        imageAlt: 'Yahoo Logo',
        imageHeight: 55,
        imageWidth: 200,
        quoteURL: 'https://finance.yahoo.com/finance/news/prepare-housing-market-crash-2021-120051439.html',
        catchPhrase: "What’s different today from what we saw in 2008",
        remainder: "is that people who are qualifying for loans are actually qualified. They are creditworthy.",
        newsOutlet: 'Yahoo!',
    },
    {
        imagePath: '/images/press/USAToday.svg',
        imageAlt: 'USA Today Logo',
        imageHeight: 70,
        imageWidth: 300,
        quoteURL: 'https://www.usatoday.com/story/sponsor-story/mbanc/2021/03/22/how-unconventional-approach-mortgages-helped-two-entrepreneurs/4725567001',
        catchPhrase: "MBANC has a different view on how you should qualify for a mortgage.",
        remainder: "The lender personalizes the qualification process and looks at you holistically.",
        newsOutlet: 'USA Today',
    },
    {
        imagePath: '/images/press/TheSun.svg',
        imageAlt: 'The Sun Logo',
        imageHeight: 87,
        imageWidth: 200,
        quoteURL: 'https://www.the-sun.com/money/3288694/how-pay-off-mortgage-years-early',
        catchPhrase: "Although it might feel good to know you fully own your home,",
        remainder: "there might be more financially savvy places to put your money.",
        newsOutlet: 'The Sun',
    },
    {
        imagePath: '/images/press/USAToday.svg',
        imageAlt: 'USA Today Logo',
        imageHeight: 70,
        imageWidth: 300,
        quoteURL: 'https://www.usatoday.com/story/sponsor-story/mbanc/2021/02/18/self-employed-and-want-buy-home-process-easier-than-expected/6769814002',
        catchPhrase: "Because MBANC is funded by private investors looking for entrepreneurs to whom they can lend,",
        remainder: "it controls all of its loan analysis and decision-making.",
        newsOutlet: 'USA Today',
    },
    {
        imagePath: '/images/press/NationalMortgageNews.svg',
        imageAlt: 'National Mortgage News Logo',
        imageHeight: 25,
        imageWidth: 300,
        quoteURL: 'https://www.nationalmortgagenews.com/news/non-qm-lender-mbanc-underwrites-borrower-income-from-mobile-wallets',
        catchPhrase: "Mbanc is a direct-to-consumer non-qualified mortgage lender",
        remainder: "whose customer base includes business owners who accept online payments for their products and services.",
        newsOutlet: 'National Mortgage News',
    },
    {
        imagePath: '/images/press/Bankrate.svg',
        imageAlt: 'Bankrate News Logo',
        imageHeight: 60,
        imageWidth: 140,
        quoteURL: 'https://www.bankrate.com/mortgages/how-to-buy-a-house-with-low-income/',
        catchPhrase: '“There are a few other strings attached, too: If you are a first-time buyer,',
        remainder: 'you will be required to go through a homeownership education program,” adds Tabitha Mazzara',
        newsOutlet: 'Bankrate',
    },
    {
        imagePath: '/images/press/GoBankingRates.svg',
        imageAlt: 'GoBankingRates News Logo',
        imageHeight: 45,
        imageWidth: 180,
        quoteURL: 'https://www.gobankingrates.com/loans/mortgage/pros-cons-online-mortgage-lenders/',
        catchPhrase: 'We’ve made it easy to do everything from your couch',
        remainder: '',
        newsOutlet: 'GoBankingRates',
    },
];
